export const ultra = {
    "Advanced Audio Preset": 0,
    "Allow Bnet Friends Join": 1,
    "Allow Chat": 1,
    "Always Run": 1,
    "Ambient Occlusion Quality": 1,
    "Anti Aliasing": 1,
    "Atmospherics Quality": 4,
    "Audio AdvancedAmbient Preset 0": 100,
    "Audio AdvancedCombat Preset 0": 100,
    "Audio AdvancedItems Preset 0": 100,
    "Audio AdvancedMonsters Preset 0": 100,
    "Audio AdvancedPlayerSkills Preset 0": 100,
    "Audio AdvancedSFX Preset 0": 100,
    "Audio AdvancedUI Preset 0": 100,
    "Audio AdvancedVO Preset 0": 100,
    "Auto Gold Enabled": 1,
    "Auto Party Invite": 1,
    "AutoMap Centers": 1,
    "AutoMap Party": 1,
    "AutoMap Party Names": 1,
    "AutoMapFade": 0,
    "AutoMapFadeAllCustomOpacity": 50,
    "AutoMapMode": 2,
    "Automap Room Name and Password": 1,
    "Blended Shadows": 0,
    "Camera Shake": 1,
    "Character Detail": 2,
    "Chat Background": 0,
    "Chat Font Size": 1,
    "Chat Gem Mode": 1,
    "Color Blind Mode": 0,
    "Color Blind Strength": 100,
    "Combat Feedback": 0,
    "Contrast": 100,
    "Controller Cursor Speed": 2800,
    "Controller Feedback": 0,
    "Controller Rumble Enabled": 1,
    "Controller Swap Thumbsticks": 0,
    "Controller Weapon Swap Separate Bindings": 0,
    "Default Key Bindings": 0,
    "Dynamic Resolution Scaling": 0,
    "Environment Detail": 2,
    "First Time": 1,
    "Framerate Cap": 0,
    "Framerate Target": 0,
    "Game Resolution": 1,
    "Gamma": 155,
    "GammaHD": 2400,
    "Graphic Presets": 4,
    "Graphics Mode": 0,
    "GreetingsSubtitles": 0,
    "HDRContrast": 1000,
    "Help Menu": 1,
    "Item Name Display": 0,
    "Item Tooltip Hotkey Appender": 1,
    "Language": 0,
    "Light Quality": 2,
    "Lobby Allow Bnet Friends Join": 1,
    "Lobby Difficulty": 0,
    "Lobby Level Difference Enabled": 0,
    "Lobby Max Difference": 10,
    "Lobby Max Players": 8,
    "Lobby Wide Item Drop Enabled": 1,
    "Low Vision Mode": 0,
    "Master Volume": 100,
    "Max Difference": 10,
    "Max Difference Enabled": 0,
    "Max Players": 8,
    "MaxLuminance": 10000,
    "Mono Mode": 0,
    "Music Volume": 100,
    "NPC Speech": 2,
    "NVIDIA DLSS": 0,
    "PaperWhiteNits": 1000,
    "Perspective": 0,
    "Resolution Scale": 50,
    "Safe Screen Percent": 100,
    "Screen Resolution (Windowed)": "1280x941",
    "Shadow Quality": 1,
    "Sharpening": 0,
    "Show Clock": 1,
    "Show HP Text": 0,
    "Show MP Text": 1,
    "Skill Ammo Feedback": 0,
    "Subtitles": 1,
    "TTS Speed": 50,
    "TTS Volume": 100,
    "Text to Speech": 0,
    "Texture Anisotropy": 0,
    "Texture Quality": 5,
    "Transparency Quality": 3,
    "Tutorial": 3,
    "VSync": 1,
    "Verb Disable": 0,
    "Vfx Lighting Quality": 3,
    "VoiceLanguage": 0,
    "Wide Item Drop Enabled": 1,
    "Window Mode": 0
}
