

type Ran<T extends number> = number extends T ? number :_Range<T, []>;
type _Range<T extends number, R extends unknown[]> = R['length'] extends T ? R[number] : _Range<T, [R['length'], ...R]>;

export type ClientSettings = {
    "Advanced Audio Preset": 0 | 1,
    "Allow Bnet Friends Join": 0 | 1,
    "Allow Chat": 0 | 1,
    "Always Run": 0 | 1,
    "Ambient Occlusion Quality": 0 | 1,
    "Anti Aliasing": 0 | 1,
    "Atmospherics Quality": 4,
    "Audio AdvancedAmbient Preset 0": Ran<100>,
    "Audio AdvancedCombat Preset 0": Ran<100>,
    "Audio AdvancedItems Preset 0": Ran<100>,
    "Audio AdvancedMonsters Preset 0": Ran<100>,
    "Audio AdvancedPlayerSkills Preset 0": Ran<100>,
    "Audio AdvancedSFX Preset 0": Ran<100>,
    "Audio AdvancedUI Preset 0": Ran<100>,
    "Audio AdvancedVO Preset 0": Ran<100>,
    "Auto Gold Enabled": 0 | 1,
    "Auto Party Invite": 0 | 1,
    "AutoMap Centers": 0 | 1,
    "AutoMap Party": 0 | 1,
    "AutoMap Party Names": 0 | 1,
    "AutoMapFade": 0 | 1,
    "AutoMapFadeAllCustomOpacity": Ran<100>,
    "AutoMapMode": 0 | 1,
    "Automap Room Name and Password": 0 | 1,
    "Aux Battle.net": string,
    "Blended Shadows": 0 | 1,
    "Camera Shake": 0 | 1,
    "Character Detail": 0 | 1 | 2,
    "Chat Background": 0 | 1,
    "Chat Font Size": 0 | 1,
    "Chat Gem Mode": 0 | 1,
    "Color Blind Mode": 0 | 1,
    "Color Blind Strength": Ran<100>,
    "Combat Feedback": 0 | 1,
    "Contrast": Ran<100>,
    "Controller Cursor Speed": number,
    "Controller Feedback": 0 | 1,
    "Controller Rumble Enabled": 0 | 1,
    "Controller Swap Thumbsticks": 0 | 1,
    "Controller Weapon Swap Separate Bindings": 0 | 1,
    "Default Key Bindings": 0 | 1,
    "Dynamic Resolution Scaling": 0 | 1,
    "Environment Detail": 0 | 1 | 2,
    "First Time": 0 | 1,
    "Framerate Cap": 0 | 1,
    "Framerate Target": 0 | 1,
    "Game Resolution": 0 | 1,
    "Gamma": number,
    "GammaHD": number,
    "Graphic Presets": Ran<4>,
    "Graphics Mode": 0 | 1,
    "GreetingsSubtitles": 0 | 1,
    "HDRContrast": number,
    "Help Menu": 0 | 1,
    "Item Name Display": 0 | 1,
    "Item Tooltip Hotkey Appender": 0 | 1,
    "Language": 0 | 1,
    "Light Quality": 0 | 1 | 2,
    "Lobby Allow Bnet Friends Join": 0 | 1,
    "Lobby Difficulty": 0 | 1,
    "Lobby Level Difference Enabled": 0 | 1,
    "Lobby Max Difference": Ran<10>,
    "Lobby Max Players": Ran<8>,
    "Lobby Wide Item Drop Enabled": 1,
    "Low Vision Mode": 0 | 1,
    "Master Volume": Ran<100>,
    "Max Difference": Ran<10>,
    "Max Difference Enabled": 0 | 1,
    "Max Players": Ran<8>,
    "MaxLuminance": number,
    "Mono Mode": 0 | 1,
    "Music Volume": Ran<100>,
    "NPC Speech": 0 | 1 | 2,
    "NVIDIA DLSS": 0 | 1,
    "PaperWhiteNits": number,
    "Perspective": 0 | 1,
    "Resolution Scale": Ran<500>,
    "Safe Screen Percent": Ran<100>,
    "Screen Resolution (Windowed)": string,
    "Shadow Quality": 0 | 1,
    "Sharpening": 0 | 1,
    "Show Clock": 0 | 1,
    "Show HP Text": 0 | 1,
    "Show MP Text": 0 | 1,
    "Skill Ammo Feedback": 0 | 1,
    "Subtitles": 0 | 1,
    "TTS Speed": Ran<100>,
    "TTS Volume": Ran<100>,
    "Text to Speech": 0 | 1,
    "Texture Anisotropy": 0 | 1,
    "Texture Quality": Ran<10>,
    "Transparency Quality": Ran<10>,
    "Tutorial": Ran<10>,
    "User Last Online": number,
    "VSync": 0 | 1,
    "Verb Disable": 0 | 1,
    "Vfx Lighting Quality": Ran<10>,
    "VoiceLanguage": 0 | 1,
    "Wide Item Drop Enabled": 0 | 1,
    "Window Mode": 0 | 1,
}
